
name: publish

on:
  push:
    paths:
      - api/**

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the api Docker image
        run: |
          cd api && docker build . --tag ghcr.io/sc4recoin/stockpop:api
          docker push ghcr.io/sc4recoin/stockpop:api
